//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : RentaVideojuegos
	/// Data Source    : (localdb)\MSSQLLocalDB
	/// Server Version : 17.00.4025
	/// </summary>
	public partial class RentaVideojuegosDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<Alquiler>   Alquilers    { get { return this.GetTable<Alquiler>(); } }
		public ITable<Bitacora>   Bitacoras    { get { return this.GetTable<Bitacora>(); } }
		public ITable<Jugador>    Jugadors     { get { return this.GetTable<Jugador>(); } }
		public ITable<Sucursal>   Sucursals    { get { return this.GetTable<Sucursal>(); } }
		public ITable<Videojuego> Videojuegoes { get { return this.GetTable<Videojuego>(); } }

		#endregion

		#region .ctor

		public RentaVideojuegosDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public RentaVideojuegosDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public RentaVideojuegosDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public RentaVideojuegosDB(DataOptions<RentaVideojuegosDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="dbo", Name="Alquiler")]
	public partial class Alquiler
	{
		[Column("idAlquiler"),        PrimaryKey,  Identity] public int       IdAlquiler        { get; set; } // int
		[Column("idJugador"),         NotNull              ] public int       IdJugador         { get; set; } // int
		[Column("idVideojuego"),      NotNull              ] public int       IdVideojuego      { get; set; } // int
		[Column("fechaInicio"),       NotNull              ] public DateTime  FechaInicio       { get; set; } // datetime
		[Column("fechaDevolucion"),   NotNull              ] public DateTime  FechaDevolucion   { get; set; } // datetime
		[Column("totalDiasAlquiler"), NotNull              ] public int       TotalDiasAlquiler { get; set; } // int
		[Column("costoPorDia"),       NotNull              ] public decimal   CostoPorDia       { get; set; } // numeric(10, 2)
		[Column("costoTotal"),        NotNull              ] public decimal   CostoTotal        { get; set; } // numeric(14, 2)
		[Column("fechaCreacion"),     NotNull              ] public DateTime  FechaCreacion     { get; set; } // datetime
		[Column("fechaModificacion"),    Nullable          ] public DateTime? FechaModificacion { get; set; } // datetime
		[Column("estado"),            NotNull              ] public char      Estado            { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Bitacora_Alquiler_BackReference (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey=nameof(IdAlquiler), OtherKey=nameof(DataModels.Bitacora.IdAlquiler), CanBeNull=true)]
		public IEnumerable<Bitacora> Bitacoras { get; set; }

		/// <summary>
		/// FK_Alquiler_Jugador (dbo.Jugador)
		/// </summary>
		[Association(ThisKey=nameof(IdJugador), OtherKey=nameof(DataModels.Jugador.IdJugador), CanBeNull=false)]
		public Jugador Jugador { get; set; }

		/// <summary>
		/// FK_Alquiler_Videojuego (dbo.Videojuego)
		/// </summary>
		[Association(ThisKey=nameof(IdVideojuego), OtherKey=nameof(DataModels.Videojuego.IdVideojuego), CanBeNull=false)]
		public Videojuego Videojuego { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Bitacora")]
	public partial class Bitacora
	{
		[Column("idBitacora"),      PrimaryKey, Identity] public int      IdBitacora      { get; set; } // int
		[Column("idAlquiler"),      NotNull             ] public int      IdAlquiler      { get; set; } // int
		[Column("idJugador"),       NotNull             ] public int      IdJugador       { get; set; } // int
		[Column("accionRealizada"), NotNull             ] public string   AccionRealizada { get; set; } // varchar(25)
		[Column("fechaDeLaAccion"), NotNull             ] public DateTime FechaDeLaAccion { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK_Bitacora_Alquiler (dbo.Alquiler)
		/// </summary>
		[Association(ThisKey=nameof(IdAlquiler), OtherKey=nameof(DataModels.Alquiler.IdAlquiler), CanBeNull=false)]
		public Alquiler Alquiler { get; set; }

		/// <summary>
		/// FK_Bitacora_Jugador (dbo.Jugador)
		/// </summary>
		[Association(ThisKey=nameof(IdJugador), OtherKey=nameof(DataModels.Jugador.IdJugador), CanBeNull=false)]
		public Jugador Jugador { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Jugador")]
	public partial class Jugador
	{
		[Column("idJugador"),       PrimaryKey, Identity] public int    IdJugador       { get; set; } // int
		[Column("nombreCompleto"),  NotNull             ] public string NombreCompleto  { get; set; } // varchar(250)
		[Column("email"),           NotNull             ] public string Email           { get; set; } // varchar(150)
		[Column("clave"),           NotNull             ] public string Clave           { get; set; } // varchar(15)
		[Column("esAdministrador"), NotNull             ] public bool   EsAdministrador { get; set; } // bit
		[Column("estado"),          NotNull             ] public char   Estado          { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Alquiler_Jugador_BackReference (dbo.Alquiler)
		/// </summary>
		[Association(ThisKey=nameof(IdJugador), OtherKey=nameof(DataModels.Alquiler.IdJugador), CanBeNull=true)]
		public IEnumerable<Alquiler> Alquilers { get; set; }

		/// <summary>
		/// FK_Bitacora_Jugador_BackReference (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey=nameof(IdJugador), OtherKey=nameof(DataModels.Bitacora.IdJugador), CanBeNull=true)]
		public IEnumerable<Bitacora> Bitacoras { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Sucursal")]
	public partial class Sucursal
	{
		[Column("idSucursal"),  PrimaryKey,  Identity] public int     IdSucursal  { get; set; } // int
		[Column("nombre"),      NotNull              ] public string  Nombre      { get; set; } // varchar(150)
		[Column("direccion"),      Nullable          ] public string  Direccion   { get; set; } // varchar(500)
		[Column("telefono"),       Nullable          ] public string  Telefono    { get; set; } // varchar(20)
		[Column("costoPorDia"), NotNull              ] public decimal CostoPorDia { get; set; } // numeric(10, 2)
		[Column("estado"),      NotNull              ] public char    Estado      { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Videojuego_Sucursal_BackReference (dbo.Videojuego)
		/// </summary>
		[Association(ThisKey=nameof(IdSucursal), OtherKey=nameof(DataModels.Videojuego.IdSucursal), CanBeNull=true)]
		public IEnumerable<Videojuego> Videojuegoes { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Videojuego")]
	public partial class Videojuego
	{
		[Column("idVideojuego"),     PrimaryKey,  Identity] public int      IdVideojuego     { get; set; } // int
		[Column("idSucursal"),       NotNull              ] public int      IdSucursal       { get; set; } // int
		[Column("titulo"),           NotNull              ] public string   Titulo           { get; set; } // varchar(100)
		[Column("descripcion"),      NotNull              ] public string   Descripcion      { get; set; } // varchar(500)
		[Column("idCategoria"),      NotNull              ] public string   IdCategoria      { get; set; } // varchar(100)
		[Column("fechaLanzamiento"), NotNull              ] public DateTime FechaLanzamiento { get; set; } // date
		[Column("desarrolladora"),   NotNull              ] public string   Desarrolladora   { get; set; } // varchar(100)
		[Column("distribuidora"),    NotNull              ] public string   Distribuidora    { get; set; } // varchar(100)
		[Column("imagen"),              Nullable          ] public string   Imagen           { get; set; } // varchar(255)
		[Column("trailer"),             Nullable          ] public string   Trailer          { get; set; } // varchar(255)
		[Column("estado"),           NotNull              ] public char     Estado           { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Alquiler_Videojuego_BackReference (dbo.Alquiler)
		/// </summary>
		[Association(ThisKey=nameof(IdVideojuego), OtherKey=nameof(DataModels.Alquiler.IdVideojuego), CanBeNull=true)]
		public IEnumerable<Alquiler> Alquilers { get; set; }

		/// <summary>
		/// FK_Videojuego_Sucursal (dbo.Sucursal)
		/// </summary>
		[Association(ThisKey=nameof(IdSucursal), OtherKey=nameof(DataModels.Sucursal.IdSucursal), CanBeNull=false)]
		public Sucursal Sucursal { get; set; }

		#endregion
	}

	public static partial class RentaVideojuegosDBStoredProcedures
	{
		#region SpActualizarVideojuego

		public static int SpActualizarVideojuego(this RentaVideojuegosDB dataConnection, int? @idVideojuego, int? @idSucursal, string @titulo, string @descripcion, string @idCategoria, DateTime? @fechaLanzamiento, string @desarrolladora, string @distribuidora, string @imagen, string @trailer, char? @estado)
		{
			var parameters = new []
			{
				new DataParameter("@idVideojuego",     @idVideojuego,     LinqToDB.DataType.Int32),
				new DataParameter("@idSucursal",       @idSucursal,       LinqToDB.DataType.Int32),
				new DataParameter("@titulo",           @titulo,           LinqToDB.DataType.VarChar),
				new DataParameter("@descripcion",      @descripcion,      LinqToDB.DataType.Text),
				new DataParameter("@idCategoria",      @idCategoria,      LinqToDB.DataType.VarChar),
				new DataParameter("@fechaLanzamiento", @fechaLanzamiento, LinqToDB.DataType.Date),
				new DataParameter("@desarrolladora",   @desarrolladora,   LinqToDB.DataType.VarChar),
				new DataParameter("@distribuidora",    @distribuidora,    LinqToDB.DataType.VarChar),
				new DataParameter("@imagen",           @imagen,           LinqToDB.DataType.VarChar),
				new DataParameter("@trailer",          @trailer,          LinqToDB.DataType.VarChar),
				new DataParameter("@estado",           @estado,           LinqToDB.DataType.Char)
			};

			return dataConnection.ExecuteProc("[dbo].[sp_ActualizarVideojuego]", parameters);
		}

		#endregion

		#region SpEliminarVideojuego

		public static int SpEliminarVideojuego(this RentaVideojuegosDB dataConnection, int? @idVideojuego)
		{
			var parameters = new []
			{
				new DataParameter("@idVideojuego", @idVideojuego, LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[sp_EliminarVideojuego]", parameters);
		}

		#endregion

		#region SpInsertarVideojuego

		public static int SpInsertarVideojuego(this RentaVideojuegosDB dataConnection, int? @idSucursal, string @titulo, string @descripcion, string @idCategoria, DateTime? @fechaLanzamiento, string @desarrolladora, string @distribuidora, string @imagen, string @trailer)
		{
			var parameters = new []
			{
				new DataParameter("@idSucursal",       @idSucursal,       LinqToDB.DataType.Int32),
				new DataParameter("@titulo",           @titulo,           LinqToDB.DataType.VarChar),
				new DataParameter("@descripcion",      @descripcion,      LinqToDB.DataType.Text),
				new DataParameter("@idCategoria",      @idCategoria,      LinqToDB.DataType.VarChar),
				new DataParameter("@fechaLanzamiento", @fechaLanzamiento, LinqToDB.DataType.Date),
				new DataParameter("@desarrolladora",   @desarrolladora,   LinqToDB.DataType.VarChar),
				new DataParameter("@distribuidora",    @distribuidora,    LinqToDB.DataType.VarChar),
				new DataParameter("@imagen",           @imagen,           LinqToDB.DataType.VarChar),
				new DataParameter("@trailer",          @trailer,          LinqToDB.DataType.VarChar)
			};

			return dataConnection.ExecuteProc("[dbo].[sp_InsertarVideojuego]", parameters);
		}

		#endregion

		#region SpListarVideojuegos

		public static IEnumerable<Videojuego> SpListarVideojuegos(this RentaVideojuegosDB dataConnection)
		{
			return dataConnection.QueryProc<Videojuego>("[dbo].[sp_ListarVideojuegos]");
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Alquiler Find(this ITable<Alquiler> table, int IdAlquiler)
		{
			return table.FirstOrDefault(t =>
				t.IdAlquiler == IdAlquiler);
		}

		public static Bitacora Find(this ITable<Bitacora> table, int IdBitacora)
		{
			return table.FirstOrDefault(t =>
				t.IdBitacora == IdBitacora);
		}

		public static Jugador Find(this ITable<Jugador> table, int IdJugador)
		{
			return table.FirstOrDefault(t =>
				t.IdJugador == IdJugador);
		}

		public static Sucursal Find(this ITable<Sucursal> table, int IdSucursal)
		{
			return table.FirstOrDefault(t =>
				t.IdSucursal == IdSucursal);
		}

		public static Videojuego Find(this ITable<Videojuego> table, int IdVideojuego)
		{
			return table.FirstOrDefault(t =>
				t.IdVideojuego == IdVideojuego);
		}
	}
}
